export const DUMMY_USERS_SEARCH_RESULTS = {
  total_count: 1,
  incomplete_results: false,
  items: [
    {
      login: 'test',
      id: 28230318,
      node_id: 'MDQ6VXNlcjI4MjMwMzE4',
      avatar_url: 'https://avatars3.githubusercontent.com/u/28230318?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/test',
      html_url: 'https://github.com/test',
      followers_url: 'https://api.github.com/users/test/followers',
      following_url: 'https://api.github.com/users/test/following{/other_user}',
      gists_url: 'https://api.github.com/users/test/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/test/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/test/subscriptions',
      organizations_url: 'https://api.github.com/users/test/orgs',
      repos_url: 'https://api.github.com/users/test/repos',
      events_url: 'https://api.github.com/users/test/events{/privacy}',
      received_events_url: 'https://api.github.com/users/test/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0
    }
  ]
};

export const DUMMY_USER_RESULT = {
  login: 'test',
  id: 28230318,
  node_id: 'MDQ6VXNlcjI4MjMwMzE4',
  avatar_url: 'https://avatars3.githubusercontent.com/u/28230318?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/test',
  html_url: 'https://github.com/test',
  followers_url: 'https://api.github.com/users/test/followers',
  following_url: 'https://api.github.com/users/test/following{/other_user}',
  gists_url: 'https://api.github.com/users/test/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/test/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/test/subscriptions',
  organizations_url: 'https://api.github.com/users/test/orgs',
  repos_url: 'https://api.github.com/users/test/repos',
  events_url: 'https://api.github.com/users/test/events{/privacy}',
  received_events_url: 'https://api.github.com/users/test/received_events',
  type: 'User',
  site_admin: false,
  name: 'Test',
  company: null,
  blog: null,
  location: 'UK',
  email: null,
  hireable: true,
  bio: 'Software Developer',
  twitter_username: null,
  public_repos: 2,
  public_gists: 0,
  followers: 14,
  following: 0,
  created_at: '2017-04-30T18:27:20Z',
  updated_at: '2020-06-09T16:40:50Z'
};

export const DUMMY_STARRED_RESULT = [
  {
    id: 105399035,
    node_id: 'MDEwOlJlcG9zaXRvcnkxMDUzOTkwMzU=',
    name: 'puppeteer-sharp',
    full_name: 'hardkoded/puppeteer-sharp',
    private: false,
    owner: {
      login: 'test',
      id: 61471605,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjYxNDcxNjA1',
      avatar_url: 'https://avatars3.githubusercontent.com/u/61471605?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/test',
      html_url: 'https://github.com/test',
      followers_url: 'https://api.github.com/users/test/followers',
      following_url: 'https://api.github.com/users/test/following{/other_user}',
      gists_url: 'https://api.github.com/users/test/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/test/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/test/subscriptions',
      organizations_url: 'https://api.github.com/users/test/orgs',
      repos_url: 'https://api.github.com/users/test/repos',
      events_url: 'https://api.github.com/users/test/events{/privacy}',
      received_events_url: 'https://api.github.com/users/test/received_events',
      type: 'Organization',
      site_admin: false
    },
    html_url: 'https://github.com/test/puppeteer-sharp',
    description: 'Headless Chrome .NET API',
    fork: false,
    url: 'https://api.github.com/repos/test/puppeteer-sharp',
    forks_url: 'https://api.github.com/repos/test/puppeteer-sharp/forks',
    keys_url: 'https://api.github.com/repos/test/puppeteer-sharp/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/test/puppeteer-sharp/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/test/puppeteer-sharp/teams',
    hooks_url: 'https://api.github.com/repos/test/puppeteer-sharp/hooks',
    issue_events_url: 'https://api.github.com/repos/test/puppeteer-sharp/issues/events{/number}',
    events_url: 'https://api.github.com/repos/test/puppeteer-sharp/events',
    assignees_url: 'https://api.github.com/repos/test/puppeteer-sharp/assignees{/user}',
    branches_url: 'https://api.github.com/repos/test/puppeteer-sharp/branches{/branch}',
    tags_url: 'https://api.github.com/repos/test/puppeteer-sharp/tags',
    blobs_url: 'https://api.github.com/repos/test/puppeteer-sharp/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/puppeteer-sharp/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/puppeteer-sharp/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/test/puppeteer-sharp/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/test/puppeteer-sharp/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/test/puppeteer-sharp/languages',
    stargazers_url: 'https://api.github.com/repos/test/puppeteer-sharp/stargazers',
    contributors_url: 'https://api.github.com/repos/test/puppeteer-sharp/contributors',
    subscribers_url: 'https://api.github.com/repos/test/puppeteer-sharp/subscribers',
    subscription_url: 'https://api.github.com/repos/test/puppeteer-sharp/subscription',
    commits_url: 'https://api.github.com/repos/test/puppeteer-sharp/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/test/puppeteer-sharp/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/test/puppeteer-sharp/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/test/puppeteer-sharp/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/test/puppeteer-sharp/contents/{+path}',
    compare_url: 'https://api.github.com/repos/test/puppeteer-sharp/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/test/puppeteer-sharp/merges',
    archive_url: 'https://api.github.com/repos/test/puppeteer-sharp/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/test/puppeteer-sharp/downloads',
    issues_url: 'https://api.github.com/repos/test/puppeteer-sharp/issues{/number}',
    pulls_url: 'https://api.github.com/repos/test/puppeteer-sharp/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/test/puppeteer-sharp/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/test/puppeteer-sharp/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/test/puppeteer-sharp/labels{/name}',
    releases_url: 'https://api.github.com/repos/test/puppeteer-sharp/releases{/id}',
    deployments_url: 'https://api.github.com/repos/test/puppeteer-sharp/deployments',
    created_at: '2017-09-30T20:32:25Z',
    updated_at: '2020-07-02T08:54:53Z',
    pushed_at: '2020-06-19T12:04:52Z',
    git_url: 'git://github.com/test/puppeteer-sharp.git',
    ssh_url: 'git@github.com:test/puppeteer-sharp.git',
    clone_url: 'https://github.com/test/puppeteer-sharp.git',
    svn_url: 'https://github.com/test/puppeteer-sharp',
    homepage: 'https://www.puppeteersharp.com',
    size: 3856,
    stargazers_count: 1365,
    watchers_count: 1365,
    language: 'C#',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 211,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 129,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz'
    },
    forks: 211,
    open_issues: 129,
    watchers: 1365,
    default_branch: 'master'
  }
];


