name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --unshallow origin +refs/heads/*:refs/remotes/origin/*

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run ng version

      - name: Lint project
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --watch=false

      - name: Build and Deploy project
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo "Skipping deployment since this action is triggered via a PR!"
            npm run build
          else
            echo "Buiding and Deploying project!"
            npm run deploy -- --repo=https://${{ secrets.GH_TOKEN }}@github.com/exequiel09/thisdot-gh-user-search.git --name="${{ secrets.GH_DEPLOYER_NAME }}" --email=${{ secrets.GH_DEPLOYER_EMAIL }}
          fi


